version: '3.8'

services:
  flask-app:
    build: flask_car_testdrive/
    container_name: flask_app
    restart: always
    volumes:
      - /usr/src/app/

    environment:
      - REDIS_URL_LOCAL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kfLdi9234jK9L120)ld
      - POSTGRES_DB=testdrive
    volumes:
      - ./postgres-data:/var/lib/postgresql/datas/

  nginx:
#    build: deployment/nginx/
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - 80:80
#      - 443:443
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


    depends_on:
      - flask-app

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


  redis:
    container_name: redis
    image: redis:7.0
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf

    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379

  pgbackups:
    container_name: Backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - db:db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=testdrive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kfLdi9234jK9L120)ld
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@every 0h30m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81

volumes:
  postgres_data:
  redis_data:
