version: '3.8'

services:
  flask-app:
    build: flask_car_testdrive/
    container_name: flask_app
    restart: always
    environment:
      - REDIS_URL_LOCAL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kfLdi9234jK9L120)ld
      - POSTGRES_DB=testdrive

  nginx:
    image: nginx:1.25
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - flask-app

  certbot:
    container_name: certbot
    image: certbot/certbot:v2.6.0
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  redis:
    container_name: redis
    image: redis:7.0
    restart: unless-stopped
#    command:
#      - redis-server
    volumes:
      - ./deployment/redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379


  pgbackups:
    container_name: backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - db:db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=testdrive
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kfLdi9234jK9L120)ld
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@every 0h30m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81

