server {
    # listen on port 80 (http)
    listen 80;
    server_name flask-app;
    location / {
        # redirect any requests to the same URL but on https
        return 301 https://$host$request_uri;
    }

server {

    listen 443 ssl;
    server_name flask-app;
    client_max_body_size 200M;


    location flask_car_testdrive/app/static/ {
    }

    location / {
        proxy_pass http://flask-app:5000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}

