"""initial commit

Revision ID: 15e70996ad16
Revises: 
Create Date: 2023-04-19 15:22:01.300942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15e70996ad16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_menu')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('cars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id_car', sa.INTEGER(), server_default=sa.text("nextval('cars_id_car_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_brand', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('id_photos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_video', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_car', name='cars_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('id_user', sa.INTEGER(), server_default=sa.text("nextval('users_id_user_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_user', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('orders',
    sa.Column('id_order', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_car', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_car'], ['cars.id_car'], name='orders_id_car_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], name='orders_id_user_fkey'),
    sa.PrimaryKeyConstraint('id_order', name='orders_pkey')
    )
    op.create_table('main_menu',
    sa.Column('head_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('head_id', name='main_menu_pkey'),
    sa.UniqueConstraint('text', name='main_menu_text_key'),
    sa.UniqueConstraint('url', name='main_menu_url_key')
    )
    # ### end Alembic commands ###
